name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set commit metadata
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git show -s --format=%ci HEAD)" >> $GITHUB_ENV

      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID || 'proj_01JRX6XSJCDVPJ2HE3ZHZB7A4S' }}
          extra-args: --allow-dirty
          secrets: |
            AI_API_KEY = '${{ secrets.AI_API_KEY }}'
            GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}'
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            DEBUG_ROOM_ID = '${{ secrets.DEBUG_ROOM_ID }}'
            FREETALK1_ROOM_ID = '${{ secrets.FREETALK1_ROOM_ID }}'
            FREETALK2_ROOM_ID = '${{ secrets.FREETALK2_ROOM_ID }}'
            MADSISTERS_ROOM_ID = '${{ secrets.MADSISTERS_ROOM_ID }}'
            SHYBOYS_ROOM_ID = '${{ secrets.SHYBOYS_ROOM_ID }}'
            SHUTTLE_API_KEY = '${{ secrets.SHUTTLE_API_KEY }}'
            EROGAKI_ROLE_ID = '${{ secrets.EROGAKI_ROLE_ID }}'
            JAIL_MARK_ROLE_ID = '${{ secrets.JAIL_MARK_ROLE_ID }}'
            JAIL_MAIN_ROLE_ID = '${{ secrets.JAIL_MAIN_ROLE_ID }}'
            DISCORD_GUILD_ID = '${{ secrets.DISCORD_GUILD_ID }}'
            COMMIT_HASH = '${{ env.COMMIT_HASH }}'
            COMMIT_DATE = '${{ env.COMMIT_DATE }}'
